[package]
name = "uhyve"
version = "0.0.5"
authors = ["Stefan Lankes <slankes@eonerc.rwth-aachen>"]
license = "MIT/Apache-2.0"
keywords = ["hypervisor", "unikernel"]
categories = ["os"]
readme = "README.md"

description = """
A hypervisor for RustyHermit
"""

[badges]
travis-ci = { repository = "hermitcore/uhyve" }

[dependencies]
log = "0.4"
env_logger = "0.5"
aligned_alloc = "0.1"
elf = "0.0.10"
memmap = "0.7"
lazy_static = "1.4"
clap = "2"
raw-cpuid = "7.0"
bitflags = "1.2"
libc = "0.2"
nix = "0.15"
rustc-serialize = "0.3"
byteorder = "1"
nom = "3.2.0"
strum = "0.8.0"
strum_macros = "0.8.0"
gdb-protocol = "0.1"

[target.'cfg(target_os = "linux")'.dependencies.kvm-ioctls]
version = "0.*"

[target.'cfg(target_os = "linux")'.dependencies.kvm-bindings]
version = "0.*"
